namespace SpriteKind {
    export const lava = SpriteKind.create()
}
function CargaNivel (n: number) {
    sprites.destroy(niño_malo)
    tiles.setCurrentTilemap(tilemap`nivel2`)
    tiles.placeOnRandomTile(jugador, sprites.dungeon.doorClosedNorth)
    scene.cameraFollowSprite(jugador)
    fantasma = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff9999ff........
        .......f69999996f.......
        .......f99999996f.......
        ......fd99999999df......
        ......fd99999999df......
        ......fddd9999dddf......
        ......f6dbfddfbd6f......
        ......fcdcf99fcdcf......
        .......f69999996f.......
        ......fffcd696dffff.....
        ....fc999c6f6fc999cf....
        ....f96969ffff9b9b9f....
        ....f6f6f6ffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    fantasmon = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff5555ff........
        .......f55577555f.......
        .......f55755755f.......
        ......f5557557555f......
        ......f5555775555f......
        ......f5555555555f......
        ......f575f77f575f......
        ......fc7cf55fc7cf......
        .......f5555555ffff.....
        ......fffc5757c555cf....
        ....fc555c7f7f57575f....
        ....f57575ffff7f7f7f....
        ....f7f7fffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    fantasmita = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    fantasma.setPosition(160, 0)
    fantasmon.setPosition(25, 85)
    fantasmita.setPosition(67, 90)
    fantasmita.follow(jugador, 50)
    fantasma.follow(jugador, 40)
    fantasmon.follow(jugador, 30)
}
function Nivel0 (núm: number) {
    nivel = 1
    puededisparar = 1
    tiles.setCurrentTilemap(tilemap`nivel1`)
    jugador = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    controller.moveSprite(jugador)
    scene.cameraFollowSprite(jugador)
    niño_malo = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f a a f f f . . . . 
        . . . f f f a a a a f f f . . . 
        . . f f f c c c c c c f f f . . 
        . . f f c a a a a a a c c f . . 
        . . f c a f f f f f f a c f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f c c c c c c f 4 e . . 
        . . 4 d f c c c c c c f d 4 . . 
        . . 4 4 f 4 4 a a 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Enemy)
    niño_malo.setPosition(7, 100)
    info.setLife(15)
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`baston`, function (sprite, location) {
    if (tienebaston == 0) {
        tienebaston = 1
        puededisparar = 0
        game.showLongText("\"CONSEGUIDO BASTON\"", DialogLayout.Top)
    }
})
function nivel3 (núm: number) {
    sprites.destroy(fantasma)
    sprites.destroy(fantasmita)
    tiles.setCurrentTilemap(tilemap`nivel0`)
    tiles.placeOnRandomTile(jugador, assets.tile`miMosaico2`)
    controller.moveSprite(jugador, 100, 0)
    jugador.ay = 400
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    sprites.destroy(projectile)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`miMosaico6`, function (sprite, location) {
    music.setVolume(167)
    music.play(music.stringPlayable("G B A G C5 B A B ", 120), music.PlaybackMode.UntilDone)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (jugador.isHittingTile(CollisionDirection.Bottom)) {
        jugador.vy = -220
    }
    music.play(music.createSoundEffect(WaveShape.Square, 405, 641, 255, 0, 200, SoundExpressionEffect.None, InterpolationCurve.Linear), music.PlaybackMode.UntilDone)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava1, function (sprite, location) {
    info.changeLifeBy(-1)
    tiles.placeOnRandomTile(jugador, assets.tile`miMosaico2`)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    tiles.placeOnRandomTile(jugador, sprites.dungeon.doorClosedNorth)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`EXIT`, function (sprite, location) {
    CargaNivel(1)
    music.setVolume(167)
    music.play(music.stringPlayable("G B A G C5 B A B ", 400), music.PlaybackMode.UntilDone)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`miMosaico0`, function (sprite, location) {
    if (tienemedicina == 0) {
        tienemedicina = 1
        game.showLongText("medicina conseguida", DialogLayout.Top)
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.doorOpenNorth, function (sprite, location) {
    nivel3(1)
    music.setVolume(167)
    music.play(music.stringPlayable("G B A G C5 B A B ", 400), music.PlaybackMode.UntilDone)
})
let tienemedicina = 0
let projectile: Sprite = null
let puededisparar = 0
let nivel = 0
let fantasmita: Sprite = null
let fantasmon: Sprite = null
let fantasma: Sprite = null
let jugador: Sprite = null
let niño_malo: Sprite = null
let tienebaston = 0
game.showLongText("Hace mucho tiempo, la IA malvada robó los 4 objetos mágicos", DialogLayout.Bottom)
game.showLongText("Solo un héroe llamado Jimmy puede recuperarlos", DialogLayout.Bottom)
game.showLongText("Encuentra los 4 objetos y salva el conocimiento ancestral de nuestros abuelos", DialogLayout.Bottom)
Nivel0(1)
let objetos = 0
tienebaston = 0
game.onUpdateInterval(1, function () {
    if (puededisparar) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 3 3 3 3 3 3 3 3 3 3 3 3 . . 
            . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . . 3 3 3 3 3 3 3 3 3 3 3 3 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, niño_malo, 100, 0)
    }
})
forever(function () {
    music.setVolume(40)
    music.play(music.createSong(hex`0078000408030105001c000f0a006400f4010a0000040000000000000000000000000000000002900000000400011b04000800011e08000c0001220c001000011b10001400011e14001800012218001c00011b1c002000011e20002400012224002800011b28002c00011e2c003000012230003400011934003800011d38003c0001223c004000011940004400011d44004800012248004c0001194c005000011d50005400012254005800011958005c00011d5c0060000122`), music.PlaybackMode.UntilDone)
})
